print("Welcome to the tip calculator app.")
bill = float(input("What was the total bill? $"))
people = float(input("How many people to split the bill? "))
tip = float(input("What percentage tip would you like to give? 10, 12, or 15? "))
total = round((bill + bill*tip/100)/people, 1)
print("Each person should pay: $" + str(total))